name: Deploy to Heroku
on: 
  push:
    branches:
      - dev
jobs:
  Deployer:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - uses: actions/checkout@v2
      - run: heroku git:remote -a polar-stream-14955
      - run: git remote -v 
      - run: git push heroku dev 
