name: practice-github-workflow
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: chabad360/htmlproofer@master
        with:
         directory: "./portfolio"			
      - run: npm install -g bats
      - run: bats -v 
 
