name: js CI
defaults:
  run:
    working-directory: js

on:
  push:
    branches: [ dev ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install modules
      run: yarn
      run: yarn add --dev jest
    - name: Run tests
      run: yarn test
